root.exe: root.c
	g++ -o  root.exe -g root.c
add.exe: add.c
	g++ -o  add.exe -g add.c
llist.exe: llist.c
	g++ -o  llist.exe -g llist.c
reverse.exe: reverse.c
	g++ -o reverse.exe -g reverse.c
minwin.exe: minwin.c
	g++ -o minwin.exe -g minwin.c
